name: Coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install cargo-tarpaulin
          run: cargo install cargo-tarpaulin
        - name: Run tests with coverage
          run: cargo tarpaulin --out Xml --ignore-tests --ignore-clippy --ignore-failures --continue --all-features --all-targets
        - name: Upload coverage
          uses: codecov/codecov-action@v3
          with:
            file: cobertura.xml
            fail_ci_if_error: true
            verbose: true